---
title: "Intrannual Time Series Plots"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# This loads in the plots, which were generated in the file named 'pt2_...'
load("all_plots_list.RData")

```

```{r, echo=FALSE, results='asis', fig.width=6.5, fig.height=7}
library(cowplot)
secchi_stations1 <- unlist(strsplit("2-APP020.23 2-LCN000.20 2-PKC001.84 2-SPE000.17 4ACRR008.32", " "))
secchi_stations2 <- unlist(strsplit("4ABSA000.62 4ABWR002.50 4ABWR010.55 4ABWR017.42 4ACCK001.80 4ACOA000.60 4AGIL002.39 4AROA158.22 4AROA163.76 4AROA167.34 4AROA175.63 4AROA180.21 4AROA183.64 4AROA192.94 4AROA196.05 4AWTH000.40 9-NEW087.14 9-NEW089.34 9-NEW092.66 9-NEW098.32 9-PKC000.00 9-PKC004.16", " "))
chlaTrends_stations <- c("4AROA038.49", "8-NAR047.69", "8-NAR054.17", "9-PKC004.16")
secchiTrends_stations <- c("1BCRO009.19", "4ASRE046.90")

stations_of_interest_10yrs <- c(secchi_stations2, chlaTrends_stations, secchiTrends_stations)
all33_stations <- c(secchi_stations1, secchi_stations2, chlaTrends_stations, secchiTrends_stations)

# Display each station's combined plots
for (station in stations_of_interest_10yrs) {
  # Print the station header as an RMarkdown header (### is level 3)
  cat("### Station: ", station, "\n\n")
  
  # Use cowplot::plot_grid to combine plots and avoid $variable issue
  combined_plot <- plot_grid(plotlist = all_plots_list[[station]], ncol = 2)
  print(combined_plot)
  
  # Add some space between stations
  cat("\n\n")
}

```


```{r, echo=FALSE, results='asis', fig.width=3.25, fig.height=3.25}
# Display Secchi only plots
for (station in secchi_stations1) {
  # Print the station header as an RMarkdown header (### is level 3)
  cat("### Station: ", station, "\n\n")
  
  plot(all_plots_list[[station]]$SECCHI_DEPTH)
  
  # Add some space between stations
  cat("\n\n")
}

```